baseurl: "https://martinhinz.github.io/ssla_conf_list/"
languageCode: en-us
title: SSLA Conference List
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/MartinHinz/ssla_conf_list
    - name: Twitter
      url: https://twitter.com/CAA_SSLA
taxonomies:
  tag: "tags"
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A list of conferences on Scientific Scripting Languages in Archaeology
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: ssla_logo.png
    width: 50
  customCss:
    - css/custom.css
